# Generated by Django 6.0.4 on 2026-04-23 08:46

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age_group',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country_id',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
